<a href="https://colab.research.google.com/github/JefeSimpson/elementsAI/blob/main/Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
for i in range(1, 6):
  for j in range(1, i + 1):
    print(j, end = ' ')
  print()

1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


In [9]:
print('Example output:')
num = int(input('Enter number '))
sum = 0
for i in range(num + 1):
  sum += i
print('Sum is:', sum)

Example output:
Enter number 10
Sum is: 55


In [15]:
nums = list(map(int, input().split()))

print('Expected output:')

for i in nums:
  if i > 500:
    break
  if i > 150:
    continue
  if i % 5 == 0:
    print(i)

12 75 180 145 525 50
75
145


In [23]:
num = int(input('The number is '))
cnt = 0
while num > 0:
   #print(num % 10)
   num //= 10
   cnt += 1
print('Digits number is:', cnt)

The number is 75869
Digits number is: 5


In [26]:
for i in range(5, 0, -1):
  for j in range(i, 0, -1):
    print(j, end = ' ')
  print()

5 4 3 2 1 
4 3 2 1 
3 2 1 
2 1 
1 


In [29]:
list1 = [10, 20, 30, 40, 50]
for i in range(len(list1) - 1, -1, -1):
  print(list1[i])

50
40
30
20
10


In [30]:
for i in range(-10, 0):
  print(i)

-10
-9
-8
-7
-6
-5
-4
-3
-2
-1


In [34]:
my_list = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
for i in range(len(my_list)):
  if (i + 1) % 2 != 0:
    print(my_list[i], end = ' ')

10 30 50 70 90 

In [42]:
import numpy
sampleArray = numpy.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])
print('Printing Original Array')
print(sampleArray)

sorted_by_row = sampleArray[:, sampleArray[1, :].argsort()]
print('\nSorting Original array by second row')
print(sorted_by_row)

sorted_by_column = sampleArray[sampleArray[:, 1].argsort()]
print('\nSorting Original array by second column')
print(sorted_by_column)

Printing Original Array
[[34 43 73]
 [82 22 12]
 [53 94 66]]

Sorting Original array by second row
[[73 43 34]
 [12 22 82]
 [66 94 53]]

Sorting Original array by second column
[[82 22 12]
 [34 43 73]
 [53 94 66]]


In [52]:
import numpy
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = numpy.array([[10,10,10]])
print('Printing Original Array')
print(sampleArray)

print('\nArray after deleting column 2')
sampleArray = numpy.delete(sampleArray, 1, axis = 1)
print(sampleArray)

print('\nArray after inserting column 2')
sampleArray = numpy.insert(sampleArray, 1, newColumn, axis =1)
print(sampleArray)



Printing Original Array
[[34 43 73]
 [82 22 12]
 [53 94 66]]

Array after deleting column 2
[[34 73]
 [82 12]
 [53 66]]

Array after inserting column 2
[[34 10 73]
 [82 10 12]
 [53 10 66]]


In [56]:
import random
import string

res = ''.join(random.choice(string.ascii_letters) for i in range(5))
print(res)

sAOSu


In [59]:
import random
import string

password = random.choices(string.ascii_uppercase, k = 2)
password += random.choice(string.digits)
password += random.choice(string.punctuation)

for i in range(6):
  password += random.choice(string.ascii_uppercase + string.ascii_lowercase)

res = ''.join(password)
print(res)

NO5'KVSECr
